### ISSUE TITLE
Event when health reaches 0?

### ISSUE THREAD

**Issue by Readie1593** [FoolishDave/BailOut#1]
Hi this is less of an issue and more if a feature that I would like to see, could you make it possible so that when your heath hits 0 the health bar turn red and the environment flashes red lights or the failed msg pops up just so that i know ive failed (but can still carry on). If you make this a feature, many thanks in advance

**Comment by dotBeeps** [comment]
Hello there! Development and maintenance of this mod was taken over by JumpmanSr. You can find his repo [here](https://github.com/JumpmanSr/BailOutMode)

**Comment by Readie1593** [comment]
> Hello there! Development and maintenance of this mod was taken over by JumpmanSr. You can find his repo [here](https://github.com/JumpmanSr/BailOutMode)

Ok thx

**Comment by Readie1593** [comment]
> Hello there! Development and maintenance of this mod was taken over by JumpmanSr. You can find his repo [here](https://github.com/JumpmanSr/BailOutMode)

Ok thx
